# Generated by Django 5.0.11 on 2025-01-18 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagevisit',
            old_name='page',
            new_name='path',
        ),
    ]
